[package]
name = "iron_rusqlite_middleware_example"
version = "0.1.0"
authors = ["Kevin Midkiff <midkiff.km@gmail.com>"]

[dependencies]
iron = "0.5.1"
iron_rusqlite_middleware = { path = "..", version = "*" }
